### ISSUE TITLE
The applet and activity pages aren't translated to French after selecting the French website language

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#101]
**Steps to reproduce**
1. Open a site https://web-staging.mindlogger.org/
2. Log in: avani_ml@protonmail.com // 12345678
3. Change the website language to French
4. Proceed to any activity
5. Start an activity
6. Pay attention to the screen

**Actual result**
The applet and activity pages aren't translated to French after selecting the French website language. 

**Expected result**
The applet and activity pages are translated to French after selecting the French website language

**Screenshot:** https://www.screencast.com/t/0BehfVmEYNN

**Environment:**
https://web-staging.mindlogger.org/
avani_ml@protonmail.com // 12345678
applet: applet 1
Applet password: Qwe123!!!

**Comment by HarutQA** [comment]
Everything works correct, buttons are translated into France.

**Comment by natalia-muzyka** [comment]
@mtg137 The issue is reproducible.

The next elements aren't translated to French:
1) the "Next" button on the summary (cumulative item) page
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/28a521f2-e1b9-4f94-89d0-6a2fbe7bd8c2)
2) the placeholder in the "A propose"(About) modal window
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/292d8379-6403-4d28-87d9-eb5074dd4fc0)

**Environment:**
https://web-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.82 
avani_ml@protonmail.com	12345678
activity based on cumulative score

**Comment by natalia-muzyka** [comment]
Verified as fixed
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/af4d5cec-3e7b-4630-81a4-d2f4e40a0510)

Environment:
https://web-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.82
maddison_ml@protonmail.com 12345678
activity based on cumulative score
