### ISSUE TITLE
Clicking on the "About" button opens applet info with HTML tags.

### ISSUE THREAD

**Issue by HarutQA** [ChildMindInstitute/mindlogger-web#108]
Steps to reproduce
1. Open https://web-staging.mindlogger.org/applet
2. Log In
3. Choose an Applet with info
4. Tap on "About" screen

Actual result
On the opened windows "About" screen Applet info is displayed with HTML tags 

Expected result
"About" screen Applet info should be displayed appropriate, without HTML tags.![Screen Shot 2021-08-20 at 16.51.51.png](https://images.zenhubusercontent.com/61125099ad96283f91ec1d29/f90bf69f-5328-46a9-ab1d-d51a038c1ec8)

Environment
MAC Safari Version 14.0.3

**Comment by jj105** [comment]
I think it's bug in applet content of tokenlogger school applet

link for readme file we need to fix:
https://raw.githubusercontent.com/ChildMindInstitute/TokenLogger_school_applet/master/protocols/TokenLogger_school/README.md
