### ISSUE TITLE
Adding an image to a tooltip does not show up on Webapp 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#113]
Steps to recreate 
1. Create an applet with radio buttons that have an image uploaded to the tooltip 
2. Check the applets on webapp 
3. See Results 

Expected - The tooltip shows an image - Please check other markdown features 
Actual - The tooltip shows URL of image 

![Resizer_16300965855281.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e37aef6b-e538-4dd8-91b2-f06e494a3d61)

**Comment by HarutQA** [comment]
Works correct.

![Screen Shot 2021-08-31 at 17.30.22.png](https://images.zenhubusercontent.com/61125099ad96283f91ec1d29/b2fa1846-537b-498d-a45a-053779ba11fd)
