### ISSUE TITLE
The "one-time completion" activity isn't hidden after completing the activity on the website

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#145]
**Preconditions**
The user is logged in on admin panel
avani_ml@protonmail.com // 12345678

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Schedule any activity (e.g. applet "token values", activity "activity1"):
- always available
- one-time completion
3. Open a webapp https://web-staging.mindlogger.org/ and log in
4. Complete the "one-time completion" activity (submit the responses)
5. Pay attention to the screen

**Actual result**
The "one-time completion" activity isn't hidden after completing the activity on the website

**Expected result**
The "one-time completion" activity is hidden after completing the activity on the website

**Video:** https://www.screencast.com/t/Zmt406kCBgT

**Environment:**
https://web-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.63 
macOS 10.15 // Safari 13.1.2
avani_ml@protonmail.com // 12345678
applet/activity:
token values / activity1
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed
Video: https://www.screencast.com/t/Fe3GPDq1N0Le

Environment:
https://web-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.82 
macOS 11.0 // Safari 14.0.1
avani_ml@protonmail.com // 12345678
applet/activity:
token values / activity1
Applet password: Qwe123!!!

**Comment by astef021** [comment]
This issue is reproduced again
test_2@protonmail.com / 123456
applet - Webapp schedule
activity - activity2

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/I62J1VKZ

Environment:
https://web-staging.mindlogger.org/
bruce_ml@protonmail.com	12345678
applet: image test
