### ISSUE TITLE
The markdown text isn't supported on the summary(cumulative item) page on the website

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#149]
**Preconditions**
The user is logged in to the website
https://web-staging.mindlogger.org/
avani_ml@protonmail.com // 12345678
There is an activity with cumulative score item and specified markdown text as a Message at or above/Out of range

**Steps to reproduce**
1. Open a site https://web-staging.mindlogger.org/
2. Proceed to activity with the cumulative item and markdown text:
applet / activity: pdf export test / cumulative activity (markdown)
3. Complete the assessment
4. Pay attention to the summary page

**Actual result**
The markdown text isn't supported on the summary(cumulative item) page

**Expected result**
The markdown text is supported on the summary(cumulative item) page

**Environment**
https://web-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.82 
avani_ml@protonmail.com // 12345678
applet / activity: pdf export test / cumulative activity (markdown)
Applet password: Qwe123!!!

**Comment by jj105** [comment]
@natalia-muzyka - I am able to see markdown on current web-staging

![image.png](https://images.zenhubusercontent.com/5e565f9bd9593e11ebab005a/a7fd0665-0c25-44da-ba1e-21d46de69d47)
could you please double check?

**Comment by natalia-muzyka** [comment]
@jj105 you are right, it is supported now.
closing a ticket, thank you!
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cd42ce96-ca94-46f8-ba9d-e3435bd7515a)
