### ISSUE TITLE
Implement Cumulative Score Item on Webapp 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#16]
As an editor, I want an applet that contains a cumulative score item to show me the results screen based on the answers I entered so that I can take an assessment on mobile or web. 

[Cumulative score original implementation ](https://github.com/ChildMindInstitute/mindlogger-applet-builder/issues/47)

Requirements 
- Implement this with scoring on webapp 
- It should function just like mobile does with all options

**Comment by HarutQA** [comment]
Fixed.
