### ISSUE TITLE
Replace Landing Page 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#176]
- The new landing page for the webapp should be https://web.mindlogger.org/applet. 
- Please also update the logo URL to https://web.mindlogger.org/applet

**Comment by natalia-muzyka** [comment]
@WorldImpex could you confirm, please:
these changes should be applied only to authorized users and under the landing page you mean the page with the "Get started" button that previously was displayed right after authorizing?

Current behavior: clicking on the "MindLogger" in the header redirects the **unauthorized** user from all the rest pages(main landing, login, reset password, create a new user) to the empty page https://web-staging.mindlogger.org/applet
Video: https://www.screencast.com/t/dxHIBYvt9

**Comment by WorldImpex** [comment]
@natalia-muzyka Yes you are correct - We need that page for unauthorized users. Let me check on what image should replace what was existing
