### ISSUE TITLE
[UI][Landing page changes] Webapp issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#189]
**1. [Dashboard][Activity page] The background is stretched due to the content**
Expected: 
The background displaying depends on the viewport size and it is fixed, so only the content moves(grows) but the background stays the same. 
Video: 
https://www.screencast.com/t/fxAtCfEuD
https://www.screencast.com/t/RGGeylqvYa
https://www.screencast.com/t/jszt5uis

**2. [Applet][Activity][Invitation][Profile] There is extra space on the top**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/487042ec-cbbe-4eb9-b83f-e1219dcd3d51)

**3. [Mobile][Login][Sign up][Activity block] Some info is not comfortable to read because of the background clouds**
Expected: The activity and forms blocks have a white background.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8b889132-74e2-49d3-876d-b8b75624ebba)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9d4197ec-65f9-46df-9876-046e1b13ce2d)

**4. [Activity page] The activity empty progress bar is almost invisible because of the background**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/139fe878-382b-4dc3-953f-9b2068e89315)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/348ed7d2-9a34-4be4-8b5e-ab861732dbe8)

**5. Margins are missing:**
Activity - right, left margins
Settings - right, left margins
Profile -  right, left margins
Activity - activity block bottom margin
Login - right, left margins
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ececd2aa-3187-4a7b-9f70-7525a41d5ee8)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/eb638a81-4315-4e8b-8f35-66f146c3c44d)

**6. The Android and iOS icons are missing on the main screen**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3b6cfe34-5487-4df1-b817-100192e97d83)

**Environment:**
Win 10 // Chrome 94.0.4606.81 
iPhone SE (2020) // iOS 14.2 // Safari
iPhone 6 Plus // iOS 12.4.8 // Safari
Samsung Galaxy S7 SM-G930FD // Android 8.0  // Chrome 94.0.4606.81

**Comment by Matchdev120** [comment]
@natalia-muzyka In the 6), the screen that Wil shared is the main idea and not a design for dashboard page I think.
@WorldImpex Would you please clarify this one and let us know?

**Comment by Matchdev120** [comment]
@natalia-muzyka Would you please check the margin 5) in setting pages again?

**Comment by natalia-muzyka** [comment]
@Matchdev120 

**Still reproducible:**
**1. [desktop][mobile] The background is resized(clouds are vertically stretched) if there are a lot of activities on the dashboard, or a lot of questions on the activity page.**
Video: https://www.screencast.com/t/p6ip5TtTsz
There is pixelization because of such resizing, the background picture looks bad.
Is it possible to make a background fixed as on the mobile app?:
https://www.screencast.com/t/sSRm5fZ0V

**4. The current activity progress bar is still badly displayed.**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8e121ce4-b4de-4751-9f10-da51f6d8c468)

**New issue:**
The logo and buttons aren't vertically aligned on the "Get started" page:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7f49b829-09d7-4fab-864c-2919c23e77a0)

**Fixed:**
#2 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8073c2ea-7d99-4299-aec7-43d3cf9f0c9e)

#3
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3cdfb0db-899b-415d-8e34-7876727f61f3)

#5 margins are smaller than previously(login, sign up, profile and settings pages) but look good:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6cd187b2-6f17-4b2e-896c-b672dc33768e)
