### ISSUE TITLE
Webapp Redirecting  landing page issue

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#200]
There are some mismatches in the current redirects after all the latest changes.

**Current behavior:**

**Authorized user:**
The user after logging in on https://web-staging.mindlogger.org/ is landed on the https://web-staging.mindlogger.org/applet page with all the applets.
The Logo redirects the authorized user from all the pages to the https://web-staging.mindlogger.org/applet (as per the requirements).
But there is still the  https://web-staging.mindlogger.org/ page which is like an orphan page now (because there is no link to this page on the site).
Video: https://www.screencast.com/t/YfdAcYAY1OEN

**Unauthorized user:**
After opening the https://web-staging.mindlogger.org/ there is a new page with updated image and app icons.
After clicking the logo, the https://web-staging.mindlogger.org/dashboard is opened (which is visually the same page but with a different address). 
Video: https://www.screencast.com/t/VyGppIbDhX
Before updating the landing page (with image and icons) after clicking the logo the unauthorized user was redirected to the empty https://web-staging.mindlogger.org/applet page.

**As per the requirements** looks like there shouldn't be https://web.mindlogger.org/ and user after entering this address should be always redirected to the https://web.mindlogger.org/applet
And if the user is:
- **unauthorized** he/she sees the updated page (with M logo image and app icons)
- **authorized** sees his/her applets
ML site logo should redirect both users always to the https://web.mindlogger.org/applet
**But I'm not sure that I understood this correctly, could anyone clarify this please, thank you!**

**Comment by Matchdev120** [comment]
@WorldImpex Would you please clarify the requirements?
Natalia and I would like to make sure the above things.

**Comment by WorldImpex** [comment]
@Matchdev120  - Yes @natalia-muzyka is correct with her requirements

**Comment by natalia-muzyka** [comment]
So, to resume, what should be changed in the current implementation:

1. There shouldn't be a https://web-staging.mindlogger.org/dashboard page for unauthorized user after clicking the ML logo. Address should be https://web-staging.mindlogger.org/applet (as per requirements as well) but it should show the new landing page with Login + Sign up, as it shows now)

2. We have https://web-staging.mindlogger.org/ for an authorized user but any button or link on the entire website doesn't point to this URL which is incorrect behavior (previously ML logo pointed to it). As well as after authorization the user is automatically redirected to the applet page and skips the https://web-staging.mindlogger.org/ . @WorldImpex I thought the landing page should be shown right after authorization. So it looks like there's no need in this page at all because authorized user has a Profile page with the same links to AppStore/PlayStore?

**Comment by Matchdev120** [comment]
@natalia-muzyka 
For me, it doesn't make sense to navigate to this URL(https://web-staging.mindlogger.org/applet) for unauthorized users. This is the page which displays all the available applets so if the user is unauthorized, then it should navigate to the other URL like dashboard or whatever.

**Comment by natalia-muzyka** [comment]
@Matchdev120 ok, I agree with you

**Comment by natalia-muzyka** [comment]
As per the discussion with @WorldImpex and @Matchdev120 the current behavior is confirmed as acceptable.
No changes were implemented on webapp. The ticket can be closed.
