### ISSUE TITLE
The webapp PDF report isn't downloaded/opened after tapping the "Share report" button

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#202]
iPhone 8 // iOS 12.3.1 // Chrome 92.0.4515.90 // Safari
Video: https://www.screencast.com/t/HjBXcLX6

iPhone X // iOS 14.6 // Safari
Video: https://www.screencast.com/t/T7bTceKI

On the other testing devices/browsers, the report is opened or required to be downloaded:
iPhone 7 // iOS 13.1.1 
// Safari - https://www.screencast.com/t/sWEn0nfwBP
// Chrome 93.0.4577.78 - https://www.screencast.com/t/R5YyCoSOQkC
iPhone X // iOS 14.6 // Chrome 95.0.4638.50 - https://www.screencast.com/t/JvMcJi4C
iPhone 12 Pro max // iOS 15.0// Chrome 95.0.4638.50

Example of the downloaded document
https://drive.google.com/file/d/1NhY0eRAKrM7F3VNJ6_zk1K381jQXstVX/view?usp=sharing

**Comment by natalia-muzyka** [comment]
@devbtech the issue is still reproducible on production:
iPhone 8 // iOS 12.3.1 // Chrome 92.0.4515.90 // Safari
Video: https://www.screencast.com/t/VOJwagUxFxP7

**Comment by natalia-muzyka** [comment]
Fixed: on iPhone X // iOS 14.6 report is opened and can be shared after tapping the "Share report"
https://www.screencast.com/t/d4hzg7u9j4

**Reproducible:**
[Safari][iPhone 6 Plus / iOS 12.4.7] The PDF report is displayed as a continuation of the summary page after tapping the "Share report"
Video: https://www.screencast.com/t/QnHJDyIOODb

[Chrome] The PDF report is still not downloaded after tapping the "Share report"
iPhone 6 Plus / iOS 12.4.7
Video: https://www.screencast.com/t/Atu4veVMwBS

Waiting for iOS 13 to test it.

**Comment by WorldImpex** [comment]
@natalia-muzyka Yes we can move that to the backlog

**Comment by natalia-muzyka** [comment]
**The issues are reproducible on the supported iOS versions and devices.**
[Safari] iPhone 8 Plus // iOS 13.3 // Chrome 93.0.4577.78
https://www.screencast.com/t/J6rzHDa1

**Comment by natalia-muzyka** [comment]
1. The main issue is reproducible now even on devices where it was working before. 
The PDF report isn't downloaded after tapping the "Share report" button.
Video: https://www.screencast.com/t/o8cKvrK26xZ

2. PDF report as a continuation of the activity page isn't reproducible anymore.

Environment:
iPad Pro 10.5 // iOS 15.0 // Safari
iPhone 6S // iOS 14.4.2
iPhone 8 Plus // iOS 13.3 // Safari

**Comment by natalia-muzyka** [comment]
@Matchdev120 after the latest changes issue is reproducible on desktop / Safari as well. 
Video: https://www.screencast.com/t/zEp8gts91JBB

Environment:
macOS 10.15 // Safari 13.1.2

**Comment by natalia-muzyka** [comment]
@Matchdev120 @devbtech 
weren't there any deploy issues? issue from the ticket is still reproducible, and I see that webapp version in header isn't changed from the previous deployment/deployments.

Video: https://www.screencast.com/t/6OeusETOv3Ho

**Comment by natalia-muzyka** [comment]
@Matchdev120 
still reproducible, and webapp version is still v0.4.0:
macOS 10.15 // Safari 13.1.2: https://www.screencast.com/t/xsQweiJw
iPhone 8 Plus // iOS 13.3: https://www.screencast.com/t/cLiP5wzsjxrP

**Comment by Matchdev120** [comment]
@natalia-muzyka I have created a PR for fixing mobile issues.

For macOS/Safari issue, I'm not able to reproduce it at all. Tested it on two devices (Mojave/Safari 14.1.2, Big Sur/Safari 15.2)
![Screen Shot 2022-01-25 at 7.16.33 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/e437d604-ee22-46d9-8a0c-98f276dbeaf2)

**Comment by natalia-muzyka** [comment]
@Matchdev120 
Fixed on macOS: https://www.screencast.com/t/Hbing9hhGMU

The issue is still reproducible on mobile devices (iPhone/iPad): https://www.screencast.com/t/ZrX1SyxG

iPhone X // iOS 14.6 // Safari
iPad Pro (10,5-inch) MQDX2 // iOS 15 // Safari
iPhone 6S // iOS 14.4.2 // Safari

**Comment by Matchdev120** [comment]
@natalia-muzyka Does it work on MacOS? or Not?
![Screen Shot 2022-02-01 at 8.19.13 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/fc12714f-8bde-455d-b629-a2226a2689b6)

**Comment by natalia-muzyka** [comment]
@Matchdev120 it doesn't work again. The top part of the comment (UPDate) is the actual behavior.

**Comment by Matchdev120** [comment]
I just tested it on my Mac. This is what I got and it works fine.
![Screen Shot 2022-02-01 at 8.51.52 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/c42ec8a7-6445-49f3-ad12-00236db2596f)

**Comment by Matchdev120** [comment]
@natalia-muzyka I used the same account and applet you used for testing.
Would you test it now?

**Comment by natalia-muzyka** [comment]
@Matchdev120 and still reproducible on mobile devices in Safari and Chrome (iOS):
https://www.screencast.com/t/mPlWoIjCfvK

iPhone 7 // iOS 13.1.1
iPhone 8 Plus // iOS 13.3
iPhone Xs Max // iOS 14.8

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/s3IbfrwM

iPhone 7 // iOS 13.1.1
iPhone 6S // iOS 14.4.2
iPhone X // iOS 14.6
iPhone XS // iOS 15.2
iPhone 11 // iOS 14.2
iPhone 12 Pro Max// iOS 15.0.1
iPhone Xs Max// iOS 14.8
iPad Pro (10,5-inch) MQDX2 // iOS 15
