### ISSUE TITLE
PDF report and summary page aren't updated accordingly to the latest requirements

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#209]
Replace You/ Your with Your #2041
Remove all text - "Remove text that says if score >= X" #2042
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/00bcd67d-bae7-4971-9c9d-c5061de4a490)

---

Add Applet Logo to the top right corner of PDF Export #135
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9ecd7668-a546-4061-999a-c998e985c326)

---

Add Splash Screen to PDF Export #2040
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d6469e3f-f635-48f7-af84-ec2136eba1dd)

---

Revert to original design of cumulative score #2043: Overview and score description are still displayed on the summary page
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/006f299b-54ed-4f84-acfe-d360895c8547)

---

**Environment:**
https://web-staging.mindlogger.org/
account: loui_ml@protonmail.com	// 12345678
applets:
Cumulative (splash screen PDF report)
Cumulative (revert summary screen) (2)
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
@binaryExDev 
**Fixed:**
Replace You/ Your with Your #2041
Remove all text - "Remove text that says if score >= X" #2042
Add Applet Logo to the top right corner of PDF Export #135
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/eb7f93a9-b96f-4956-b4bb-a5ff67821499)

---

**Reproducible:**
Add Splash Screen to PDF Export #2040 - splash screen is missing in the web PDF report

Revert to original design of cumulative score #2043: Overview and score description are still displayed on the summary page
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e893fa01-aad2-49d2-afc0-bbe19b61d81f)

**Comment by WorldImpex** [comment]
Splash screen not shown on webapp 
![Screen Shot 2021-11-15 at 5.08.47 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/fda26706-88cf-44a9-bfad-27abbf8b31a1)
Summary report fixed

**Comment by natalia-muzyka** [comment]
Splash screen is not shown on webapp as a first item [ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/213)

[iOS] The splash screen image is not displayed in the webapp PDF report #220 [ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/220)

**Comment by natalia-muzyka** [comment]
Moved a comment with not fixed issue to #2040 feature ticket
