### ISSUE TITLE
The splash screen isn't displayed on webapp

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#213]
**Actual result:** The splash screen isn't displayed on webapp
**Expected result:** Splash screen is displayed as on the mobile app: 
- the uploaded splash image/video is displayed as the first item in the activity
- there is the "Next" button on the splash item
- the splash image/video fits the item block (is adaptive) - the suggestion is to have a fixed max-width and max-height for splash item, it shouldn't take a real image/video size

**The original [mobile app ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/367)**

**Video:** https://www.screencast.com/t/4yyqgkNuup7

Applet: Splash screen test (1)
account: kimberly_ml@protonmail.com	/ 12345678

applet: splash screen (bernard)
account: bernard_ml@protonmail.com	/ qwe123!!!

**Environment:**
https://web-staging.mindlogger.org/
Win 10 // Chrome 95.0.4638.69 	
macOS 10.15 // Chrome 95.0.4638.69 	

test data:
https://c.tenor.com/zcI2ls86xsEAAAAC/dancing-chicken.gif

![100.gif](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f15f0cf7-c467-4cce-8657-1b9751e6da5c)
![100.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4ac32c35-7f06-43ed-bc70-d1817b086a41)
![1920.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/03b9db5f-8ebb-40fe-8a7d-a28dcc79d443)

**Comment by natalia-muzyka** [comment]
JPG and PNG images are displayed.
Splash screen GIF and video (mp4) are missing on the webapp.
Video: https://www.screencast.com/t/JRrRtlik0v3K

https://web-staging.mindlogger.org/
account owner: kimberly_ml@protonmail.com // 12345678
applet / activity:
splash screen test (1) / ML pediatric screener
Applet password:	Qwe123!!!

**Comment by WorldImpex** [comment]
@natalia-muzyka Lets make a separate ticket for 2 to remove the back button and then we can move this ticket to the backlog to fix the GIF/ Video on a later milestone

**Comment by natalia-muzyka** [comment]
ticket for #2
The "Back" button should be removed from the splash item on webapp [#224](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/224)

**Comment by natalia-muzyka** [comment]
GIF and MP4 are displayed in the splash item as well.
Checked on:
Environment:
https://web-staging.mindlogger.org/
Win 10 // Chrome 95.0.4638.69
Samsung S7 // Android 8.0 // Chrome
iPhone 8 Plus // iOS 13.3 // Chrome // Safari
iPad Pro 10.5 // iOS 15.0 // Chrome // Safari
Samsung Tab S6 // Android 9.0 // Chrome
Account:
kimberly_ml@protonmail.com // 12345678
applet: splash screen test (2)

waiting for MacBook to check on it

**Comment by natalia-muzyka** [comment]
Splash screen(JPEG, PNG, GIF, MP4) is displayed on webapp activity page.
#2104 is not a blocker for this ticket. Verified and closed.
