### ISSUE TITLE
[UI] The splash screen image in the PDF report isn't aligned and doesn't fit the page

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#219]
Webapp: isn't aligned vertically and horizontally and doesn't fit the page width / height
Mobile app: isn't aligned vertically
Admin panel: isn't aligned vertically

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e503cba8-bdef-4fe8-9659-93001cd4c73a)

https://web-staging.mindlogger.org/
https://admin-staging.mindlogger.org/
Samsung S7 // Android 8.0	
iPhone 8 Plus // iOS 13.3
account: kimberly_ml@protonmail.com // 12345678
applet: splash screen test (2)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@Matchdev120 there are still issues with displaying a splash image in the reports.
On all the platforms splash item should be vertically/horizontally aligned and fit the width or height (depends on what side is bigger).

account: kimberly_ml@protonmail.com // 12345678
applet: splash screen test (3)
Applet password: Qwe123!!!

Here I compare platforms (1-admin panel, 2-webapp, 3-mobile app):
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f966da79-d88e-4714-8f8b-16684bba7296)

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.45 
macOS 10.15  // Chrome 96.0.4664.45 
ML v0.17.74 (staging)
iPhone 8 Plus // iOS 13.3
Samsung S7 // Android 8

**Comment by natalia-muzyka** [comment]
@Matchdev120 there is another one thing that I've noticed on admin panel:
if there are at least two activities with splash screen, then the second (and every next) report will be shifted down:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b615f49c-568a-4e7e-858c-f7504c083d26)

PDF file: [https://app.zenhub.com/files/303774485/1ba2e0c3-22e1-4015-acce-a8744437b1b6/download](https://app.zenhub.com/files/303774485/1ba2e0c3-22e1-4015-acce-a8744437b1b6/download)

account: kimberly_ml@protonmail.com // 12345678
applet: splash screen pdf report
Applet password: Qwe123!!!

**Comment by Matchdev120** [comment]
@natalia-muzyka I cannot reproduce the last comment in `splash screen pdf report` applet.

Would you share the applet name that you tested?

**Comment by natalia-muzyka** [comment]
@Matchdev120 I can't reproduce it as well now, might there was completed one more activity that fixed displaying or so. If I'll catch it again, I'll notify you.

**Comment by natalia-muzyka** [comment]
On admin panel: 
1. there is a margin-bottom little bit bigger than a margin-top
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e96f9729-4414-4d32-a464-19586d7fbf7c)
2. if there are few splash screens, the second screen with proper size (700x1000) will be cut off(the trimmed part is moved to the next page), so a report will be shifted down
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1a9a98a1-83bb-421e-99e6-6d7c18062d48)

PDF file:
[https://app.zenhub.com/files/303774485/06007a69-2f1e-4f5f-95ac-dcf9a5e2abac/download](https://app.zenhub.com/files/303774485/06007a69-2f1e-4f5f-95ac-dcf9a5e2abac/download)

**Comment by Matchdev120** [comment]
@natalia-muzyka Would you test it on the mobile devices again?

**Comment by natalia-muzyka** [comment]
@Matchdev120 admin panel issue #1 and webapp chrome issue were fixed, right?

**Comment by natalia-muzyka** [comment]
@Matchdev120 

1. **admin panel issues #1 and #2 are reproducible again**, but only for Windows Chrome after adding some text content to the report
Screenshot:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2de37c7f-3ea2-4e28-9313-1817eb9945db)

**on macOS Safari splash screen image doesn't fit the page height** and is partially shifted to the 2nd page
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/26f14be8-ff16-4bfc-b1f4-37b318179385)

**2. nothing has changed, waiting when this fix will be deployed** 
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/220

Windows 10 // Chrome 96.0.4664.45 
macOS 0.15 // Chrome 96.0.4664.45 // Safari 13.1.2

**Comment by natalia-muzyka** [comment]
@Matchdev120 
1. waiting for #1 when it will be merged so I can check it.
2. the #2 is reproducible with valid 700x1000px image on:
- iPhone Chrome
- macOS Safari (a new behavior, previously on macOS Safari splash image wasn't displayed at all)
Video: https://www.screencast.com/t/TzEAjLfO

Environment:
https://admin-staging.mindlogger.org/
macOS 10.15 // Safari 13.1.2
iPhone 11 // iOS 14.2
account: kimberly_ml@protonmail.com // 12345678
applet: ML ped screener splash
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
testing is blocked by https://github.com/ChildMindInstitute/mindlogger-backend/issues/1165

**Comment by natalia-muzyka** [comment]
@Matchdev120 

**1.** for Windows and macOS Chrome report padding is fixed:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/59e25526-b6e7-402d-8ab6-0b2318c7f889)
**issue:** on macOS Safari the splash image is still broken into two parts and shifted to the next page:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c0a0724b-8b35-4880-a40d-05ac5cf5fe4c)

**2.** issue is still reproducible on some devices on iPhone / Chrome. macOS and iOS Safari I can't retest because of the [blocker #202](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/202) 
iPhone Chrome / Video: https://www.screencast.com/t/J0Fv4HnrP
Devices (reproducible  issue):
iPhone 11 // iOS 14.2 // Chrome 94.0.4606.52
iPhone 8 Plus // iOS 13.3 // Chrome 93.0.4577.78

**Comment by natalia-muzyka** [comment]
@Matchdev120 @devbtech 
Issues with broken splash image are still reproducible.
Weren't there any deployment issues?
Admin panel version hasn't changed with the latest deployment/deployments.
Video: 
https://www.screencast.com/t/Jk7oBs95nmxV
https://www.screencast.com/t/uonnn6Rcq3Q

**Comment by natalia-muzyka** [comment]
@Matchdev120 
on macOS Safari the splash image is still broken into two parts and the second part is shifted to the next page:
https://www.screencast.com/t/HGkRzqNZipK3

account: kimberly_ml@protonmail.com	12345678
applet (newly created): splash image test

**Comment by natalia-muzyka** [comment]
@Matchdev120 
macOS 10.15 / Safari: in admin panel and webapp report the splash image 700x1000px is still incorrectly displayed.

Video (website): https://www.screencast.com/t/fawApfnbYCN7
Video (admin panel): https://www.screencast.com/t/sHUvKmLDwcK

Environment:
https://web-staging.mindlogger.org/
MacBook Pro (13-inch, 2018) // Catalina 10.15.6 // Safari 13.1.2 (15609.3.5.1.3)
kimberly_ml@protonmail.com / 12345678
pdf report test, cumulatives (Kimberly)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Reproducible on:
iPhone 8 Plus // iOS 13.3 // Chrome 
iPhone SE (2020)	// iOS 14.2 // Safari
iPhone 11 // iOS 14.2 // Chrome // Safari
iPhone 6S // iOS 14.4.2 // Chrome // Safari

**Comment by natalia-muzyka** [comment]
@mtg137 @devbtech was there any deployment issue? admin panel still has broken splash images.
and there's no new android build to retest.

Environment:
loui_ml@protonmail.com	12345678
applet: daisy chain loop / activity 3
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
@mtg137 @WorldImpex 

- On admin panel splash screens will be broken if the first report is big and takes more than one page. If report is not bigger than one page then splash screens are displayed as expected:
https://www.screencast.com/t/Gza6EGGEYId

- On mobile app splash screen doesn't fill the full page now (fits the page height):
https://www.screencast.com/t/8ItYPkekK

@WorldImpex are these two blockers for launch?

**Comment by WorldImpex** [comment]
No @natalia-muzyka

**Comment by natalia-muzyka** [comment]
Closed due to irrelevance. Cumulative item is removed. Issue is not reproducible in the redesigned PDF report.
