### ISSUE TITLE
[iOS/Safari][macOS/Safari]Applet image is missing on the webapp

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#221]
Video: https://www.screencast.com/t/kFKZGbCebi

https://web-staging.mindlogger.org/
macOS 10.15 // Safari 13.1.2
iPhone 8 Plus // iOS 13.3 // Safari // Chrome
iPad Pro 10.5 // iOS 15.0 // Safari // Chrome
account: kimberly_ml@protonmail.com // 12345678
applet: splash screen test (2)
Applet password: Qwe123!!!

**Comment by Matchdev120** [comment]
@natalia-muzyka I think this ticket is duplicated (#221 includes this issue)

**Comment by natalia-muzyka** [comment]
@Matchdev120 @WorldImpex 
The issue is still reproducible on Safari, but **not reproducible on Chrome** 
Video: https://www.screencast.com/t/h4wWy3ByD

Environment:
https://web-staging.mindlogger.org/
macOS 10.15 // Safari 13.1.2
iPad Pro 10.5 // iOS 15.0 // Safari 
iPhone 6S // iOS 14.4.2

**Comment by natalia-muzyka** [comment]
Fixed on macOS: https://www.screencast.com/t/4amKQzCE1BVH
Testing is blocked on iOS by: [The webapp PDF report isn't downloaded/opened after tapping the "Share report" button#202](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/202)

**Comment by natalia-muzyka** [comment]
Reproducible on:
iPhone 12 Pro Max// iOS 15.0.1 // Safari
MacBook Air (M1, 2020) // macOS 12.0.1 // Safari 15.1 (17612.2.9.1.20)
https://images.zenhubusercontent.com/303774485/a6a8680c-52af-4389-aef0-c6a90a1a9e56/safari_15_website.mp4
https://images.zenhubusercontent.com/303774485/216c22b3-5d26-4714-9bd2-97c6df48f3d8/admin_safari_15.mp4

**Comment by natalia-muzyka** [comment]
Reproducible on:
macOS Catalina 10.15 // Safari 13.1.2
iPhone 11 Pro Max // iOS 13.3 // Chrome 92 // Safari
iPhone XS // iOS 13.4 // Chrome 92 // Safari

Video; https://www.screencast.com/t/6UQUeBXlAw5k

Not reproducible:
macOS Catalina 10.15 // Chrome 100
macOS BigSur 11.0 // Chrome 100 // Safari 14.1
macOS Monterey 12.0 // Chrome 100 // Safari 15.3
iPhone 13 // iOS 15.4 // Chrome 92 // Safari
iPhone 12 Pro // iOS 14.4 // Chrome 92 // Safari

**Comment by natalia-muzyka** [comment]
The issue is irrelevant, the cumulative item is removed.
