### ISSUE TITLE
The splash item(video, gif) is automatically restarted after every confirmed response (clicking the "Next" button)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#227]
**Actual result:**
If the splash video **wasn't paused**(video, gif), then it continues playing after clicking the "Next" button on it.
If the splash video **was paused**(video), then it is automatically restarted after every next confirmed response (clicking the "Next" button).
This also causes a bad user experience especially on iPhone, 'cause video is every time automatically displayed in full-screen mode and the user needs to exit it every time to continue the activity.

**Expected result:**
The splash video/gif stops playing after clicking the "Next" button on it (no matter was it paused or not).

**Video (desktop):**
https://www.screencast.com/t/UBBRZn4H8

**Video(iPhone):**
https://www.screencast.com/t/wJAHgYe7

**Environment:**
https://web-staging.mindlogger.org/
Win 10 // Chrome 95.0.4638.69
Samsung S7 // Android 8.0 // Chrome
iPhone 8 Plus // iOS 13.3 // Chrome // Safari
iPad Pro 10.5 // iOS 15.0	 // Chrome // Safari
Samsung Tab S6 // Android 9.0 // Chrome
Account:
kimberly_ml@protonmail.com // 12345678
applet: splash screen test (2)
activities: 
pc mp4 1920x1920
pc 200x200 gif + cumulatives

**Comment by natalia-muzyka** [comment]
Blocked by User can't sign in, log in or reset password on webapp#1165

**Comment by natalia-muzyka** [comment]
@mtg137 Fixed for video: 
desktop: https://www.screencast.com/t/wLOQTd1dy
mobile: https://www.screencast.com/t/qy2DJWFoEbgN

Issue: GIF-animation still continues replaying automatically. GIF should stop as a video do (if user still is on splash item and video/GIF is ended, or clicks "Next"). 
Video: https://www.screencast.com/t/F374l2yO4

**Comment by mtg137** [comment]
I think the issue involves two parts
1 - stop gif animation when user is on splash item and it is ended
2 - or click next

I fixed 2nd issue on [this PR](https://github.com/ChildMindInstitute/mindlogger-web/pull/233), but for the first issue I think it would be best to edit gif file using photoshop before uploading as there isn't elegant way to update gif file programmatically so that it plays only once

![image.png](https://images.zenhubusercontent.com/5fbce3e9259bafeab239c8c3/9f822de5-ea1e-4513-ab20-44f2ac175929)

**Comment by natalia-muzyka** [comment]
@mtg137  I just described the previously implemented mobile app behavior as expected, 
thank you for the clarification!

issue #2 verified as fixed,
video: https://www.screencast.com/t/aTCKHW9dDp

Environment:
macOS 10.15 // Safari 13.1.2 // Chrome 96.0.4664.45
Win 10 // Chrome 96.0.4664.45
iPhone 6S // iOS 14.4 // Safari 
iPhone 8 Plus // iOS 13.3 // Safari // Chrome
Samsung Tab S6 // Android 9 // Chrome
Samsung S7 // Android 8 // Chrome
