### ISSUE TITLE
[UI] The incorrect displaying of the images (response options, header images, markdown images) on the activity page

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#234]
**#1 Header image: Height is the same(1920px) but the different width/ratio (1920 vs 1000) makes the height displaying different**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/bedcbcac-19cb-4741-ab75-4064b6288d77)

**#2 Response options image (101x1920)**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/0987493f-89e4-46c4-b368-bfeb2e635fd1)

**#3 The markdown image is displayed on the same row with a text though in the applet builder it is on the next row**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/36073e1a-c13b-42a9-9e38-bf5e24e33a16)

**#4 The applet image is too big on the activity page in the portrait mode on the Tab S6 and iPad Pro 10.5**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1117fbf8-a953-4d4e-b355-1ef520ad043a)

Win 10 // Chrome 96.0.4664.45 
macOS 10.15 // Chrome 96.0.4664.45 // Safari 13.1.2
iPad Pro 10.5 // iOS 15 // Safari // Chrome
Samsung Tab S6 // Android 9 // Chrome
Samsung S7 // Android 8 // Chrome
iPhone 8 Plus // iOS 13.3 // Safari // Chrome

account: kimberly_ml@protonmail.com	12345678
applet: all items
activity: regular
Applet password:	Qwe123!!!

**Comment by astef021** [comment]
I fixed #2 and #3 in [this PR](https://github.com/ChildMindInstitute/mindlogger-web/pull/247)

but for #1 I think if we make height static, users probably need to scroll left and right side to view image like 1920 * 1000

**Comment by WorldImpex** [comment]
@astef021 Yes I think making the size of the image static will resolve this

**Comment by natalia-muzyka** [comment]
need to retest on macOS/Safari

---

**#2 is fixed:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/83c538ba-87a9-4fb0-aa2e-9fe6328381ed)

**#3 is fixed:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da
92/f46fb99e-715c-479c-b187-ecf70db5150b)

**#4 is fixed:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3a358ee2-5a74-4a64-bb9f-6448f1ff844d)

Win 10 Chrome // 96.0.4664.45 // 1920x1080 // 1366x768 // 1440x900 // 1536x864
iPad Pro 10.5 // iOS 15.0.2 // Safari // Chrome
iPhone 11 // iOS 14.2 // Chrome 94.0.4606.52
Samsung S20 // Android 11 // Chrome
iPhone 12 Pro Max // iOS 15.0 // Safari // Chrome
iPhone SE 2020 // iOS 14.2 // Safari // Chrome
iPhone 12 Pro Max // iOS 15.0 // Safari // Chrome

**Comment by natalia-muzyka** [comment]
need to retest on macOS/Safari

**Comment by natalia-muzyka** [comment]
Verified as fixed on macOS 10.15 Safari as well
