### ISSUE TITLE
[UI][Desktop version] The splash image/video is displayed too big(not fully) or too small on the activity page (depends on image/video ratio)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#235]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/473b3ba6-c6e6-4013-bdcc-28e82506b5b5)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e1bbe8df-207b-4eb7-b130-5af3a3694a39)

**Expected:** 
There should be min/max width and height for content in the splash item so even if the image/video with an uncommon ratio is uploaded it can be correctly displayed and the user doesn't need to scroll (or scale, enter fullscreen if it is a video), at least on desktop with the most common resolutions:
1920x1080
1366x768 
1440x900 
1536x864 

account:
kimberly_ml@protonmail.com // 12345678
applet: splash screen test (2)

Uploaded images:
https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e247657e-6468-413b-8b57-8d6ac79ed7e5

Uploaded videos:
https://images.zenhubusercontent.com/103405139/8d30ed8e-634f-4f06-88c8-1e80a82eaa79/file_example_mp4_1280_10mg.mp4

Environment:
https://web-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.45 // 1920x1080
MacBook Pro 13-inch // macOS 10.15 // Safari 13.1.2 // Chrome 96.0.4664.45 //  2560x1600

**Comment by natalia-muzyka** [comment]
Currently, the required splash image size that should be displayed without any issues is 700x1000px. 
Because of the latest changes due to this report, there are new UI issues on desktop and mobile devices:

**1. Mobile.Portrait: There is too big margin-top and bottom on the splash screen item**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cc4ef18a-1d9a-435c-ad45-33ca363533e5)
iPhone 11 // iOS 14.2 // Chrome 94.0.4606.52
iPhone 8 Plus // iOS 13.3 // Chrome 93.0.4577.78
Samsung S20 // Android 11 // Chrome
iPhone 12 Pro Max // iOS 15.0 // Safari // Chrome

**2. Mobile.Tablet.Landscape/Desktop: The splash image is displayed out of its block and overlaps the Next button:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/14256989-a4a2-4014-af2c-91382a2d612c)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/33fedb1d-787f-4b41-83ae-17a90270e086)
Windows 10 // Chrome 96.0.4664.45
iPhone 11 // iOS 14.2 // Chrome 94.0.4606.52
iPhone 8 Plus // iOS 13.3 // Chrome 93.0.4577.78
Samsung S20 // Android 11 // Chrome
iPhone 12 Pro Max // iOS 15.0 // Safari // Chrome

@WorldImpex could you confirm, please, do we need to fix this now as we confirmed the 700x1000px size:
**3. Splash image should take the max block height or width, doesn't matter what is the real image size**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c4c60179-4400-48a7-8961-cc39421791d5)

account:
kimberly_ml@protonmail.com // 12345678
applet: splash screen test (3), splash retest, splash requirements, ML ped Screener splash

**Comment by astef021** [comment]
I fixed #1 and #2 on the PR
@natalia-muzyka - for #2, could you reload page every time you change width/height of screen in chrome developer tool?

https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/33fedb1d-787f-4b41-83ae-17a90270e086

**Comment by natalia-muzyka** [comment]
#1 is fixed for:
iPhone 11 // iOS 14.2 // Chrome 94.0.4606.52
Samsung S20 // Android 11 // Chrome
iPhone 12 Pro Max // iOS 15.0 // Safari // Chrome
iPhone SE 2020 // iOS 14.2 // Safari // Chrome
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a168d9df-da10-4636-b137-d90fd4f13c8d)

#2 is fixed for:
Win 10 Chrome // 96.0.4664.45 // 1920x1080 // 1366x768 // 1440x900 // 1536x864
iPad Pro 10.5 // iOS 15.0.2 // Safari // Chrome
Video: https://www.screencast.com/t/PArRLgzx
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c8eeb983-1b63-419c-8d32-d4c55551f437)

**Comment by natalia-muzyka** [comment]
@WorldImpex as we confirmed the required splash image size 700x1000px I can close this ticket.

**Comment by natalia-muzyka** [comment]
Verified as fixed on macOS 10.15 // Safari 13.1.2
