### ISSUE TITLE
[PROD] Terms  & Conditions Page has white text for radio button 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#255]
Steps to recreate 
1. Sign into  production account on webapp 
2. Open Ped Screener activity 
3. See Terms and conditions page 
4. See results 

Expected: User sees the radio button in black 
Actual: The text for the response option is white 

Please duplicate the applet and add the text 

![unnamed.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/cf7a46ac-6492-4b87-a3d1-c27bfb22296d)

**Comment by natalia-muzyka** [comment]
@devbtech @WorldImpex 
could anyone share the account login/password?

**Comment by natalia-muzyka** [comment]
verified as fixed on prod account:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8106467b-d1d8-45f6-9fcf-8d0ebf582a4a)

Win 10 // Chrome 96.0.4664.93
