### ISSUE TITLE
[UI] CMI logo is stretched horizontally in the website footer

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#274]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9caab43e-b675-422a-a439-c78727411fc0)

Environment:
https://web-staging.mindlogger.org/ (v0.6.0)
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) // macOS 10.15 // Safari 13.1.2 // 2560x1600
iPhone 8 Plus	14.3	1080x1920	5,5	16:9 // Safari // Chrome 93.0.4577.78
iPhone 11	14.2	828x1792 	6.1"	19.5:9 // Safari // Chrome 96.0.4664.101
iPhone 6s	14.4	750x1334	        4,7"	16:9 // Safari // Chrome 96.0.4664.53

**Not reproducible on:**
Samsung Galaxy S7 SM-G930FD	8.0	1440x2560	5.1"	16:9 // Chrome 96.0.4664.104
iPad Pro (10,5-inch) MQDX2	15	1668x2224	10.5"	4:3 // Safari // Chrome 96.0.4664.101

**Comment by WorldImpex** [comment]
works as expected
