### ISSUE TITLE
Update Email and Webapp Invitation Text 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#291]
Update text to align with [this document](https://docs.google.com/document/d/1a5VK9-HgbcZEwE7fK9RGTresJJ9tDvJkkAHH5guph3Q/edit?usp=sharing)

1. Disregard the custom text entry. That is a future feature
2. Only show the words in red if the invitation is sent to a new user 
3. Ensure the sender and subject is updated as well

**Comment by natalia-muzyka** [comment]
Waiting for fix: 
The "Your invitation has already been removed." is displayed after an attempt to accept the pending invitation #300

**Comment by natalia-muzyka** [comment]
@WorldImpex French version is out of the scope, right? Do I need to create a separate ticket for it?

**Comment by WorldImpex** [comment]
Lets create a separate ticket for that - I will have to get some translations. Great point @natalia-muzyka

**Comment by natalia-muzyka** [comment]
@WorldImpex transfer ownership invitation should be updated as well? 
If so, how this part should be updated? "...to become a [owner]..."?

> You have been invited to become a [user, reviewer, and/or manager] of [Applet_Name].

**Comment by WorldImpex** [comment]
@natalia-muzyka Unless the copy is broken for transfer ownership then we can leave it as it is

**Comment by natalia-muzyka** [comment]
Sender is not updated in the invitation email #303 is backlogged.

Requirements are met.
Verified on:
https://web-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.82 
macOS 10.15 // Chrome 98.0.4758.82
