### ISSUE TITLE
[PROD] User can't log in, sign in, reset password on website

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#297]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8deea8ca-6dc9-4ebe-816d-83f7a4315672)

avani_ml@protonmail.com	`12345678`
danielle_ml@protonmail.com	qwe123!!!
kimberly_ml@protonmail.com	`12345678`
samanyu3@vqsprint.com	123456

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/lqVb77vnkLQ

https://web-staging.mindlogger.org/
Win 10 //  Chrome 97.0.4692.99

**Comment by natalia-muzyka** [comment]
The issue is reproducible again:
https://www.screencast.com/t/accE9q5CujA8

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/o6uoYAYxx

https://web-staging.mindlogger.org/
Win 10 // Chrome 97.0.4692.99

**Comment by natalia-muzyka** [comment]
The issue is reproducible again:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7ef91a38-e193-4232-9a4f-01d2d4540ebb)

https://web-staging.mindlogger.org/
Win 10 // Chrome 99.0.4844.51

**Comment by natalia-muzyka** [comment]
Verified as fixed; https://www.screencast.com/t/RrRFCQGfWHM

https://web-staging.mindlogger.org/
Win 10 // Chrome 99.0.4844.51

**Comment by natalia-muzyka** [comment]
The issue is reproducible on production.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4ecdb975-37a7-486e-96c2-f4037fb31432)

**Comment by WorldImpex** [comment]
@natalia-muzyka I tried avani_ml@protonmail.com 12345678 in my dimension and it works as expected.

**Comment by natalia-muzyka** [comment]
@WorldImpex @devbtech 
pay attention to the footer, why there is "terms of service" on the production website? do you have it too?
I'm still not able to log in.

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/3KJDxnZ1iS
