### ISSUE TITLE
Webapp Radio Button Activity  

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#3]
As a user, I want to complete an activity that contains radio buttons so that I can provide data to a study 

Requirements 
* If an activity is selected then show the first item type
* When the user completes an item, the next item should stack at the top so the user does not have to scroll unless he or she wants to see previously answered questions 
* Allow the user to change previously-stored answers by selecting back which will move the selected question and editability backward until the user is at the item that should be edited. 
* Radio button is in scope for this effort 
** Stack response options of radio in two columns 
* Show a confirmation screen after the user hits submit 
* If the user navigates away from the webapp and comes back later to restart an activity, show a confirmation pop like on mobile "Resume Activity - Would you like to resume this activity in progress or restart?" With Restart and Resume buttons 
* Display header and response option images 
* Show Tooltips created in the applet builder

**Comment by Matchdev120** [comment]
@devbtech The auto-advance option should be considered.

**Comment by natalia-muzyka** [comment]
**Issues**:
1) **[UI] The response option images aren't displayed**
https://www.screencast.com/t/2n3UWLSKcisS
2) **[UI] The tooltips aren't displayed after hovering the response options (radio buttons)** https://www.screencast.com/t/H7PUKP7C
3) **[UI] uploaded images are horizontally stretched**
https://www.screencast.com/t/uPYZxt9QhBH

**Questions** (are these things in scope of Milestone 6):
1) **there is an ability to proceed to the next question without selecting the answer** ("next" button is displayed permanently)
https://www.screencast.com/t/4hgshfBxFt3M
2) **the blank page is displayed after completing the activity(submitting the response).**
after proceeding to the dashboard the applet with completed activity is missing.
it is shown up only after relogin and contains unexpected activities (from a different applet).
activity stays in progress, submitted data aren't stored (no responses on admin panel)"
https://www.screencast.com/t/WJ5Ftipskacc
https://www.screencast.com/t/BjU6orSER
3) **there is the ability to edit previously-stored items without clicking "back"**
https://www.screencast.com/t/qt8P1vXIw
4) **[UI] the "submit" button has an additional border after rejectin the response submit**
https://www.screencast.com/t/loGmsZID
5) **the next options have no impact on displaying the activity:**
option settings: token value, skippable item, text input option, randomize response option,
activity settings: "allow user to skip all items", "disable the user's ability to change the response"

**Environment**
https://web-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
geria2.test@gmail.com // McgzF127
"Webapp test" applet

**Comment by WorldImpex** [comment]
@natalia-muzyka 

Issues:
Please make individual bugs for these 

Questions (are these things in scope of Milestone 6):
1) Yes please create a ticket
2) Please create a ticket. The expectation is a confirmation screen like mobile is shown
3) Please create bug ticket. The expectation is the user needs to use the back button to get back to a question to change it. This impacts conditional logic 
4) Bug it
5) This is not scope for milestone 6 so no worries

**Comment by natalia-muzyka** [comment]
All the issues are fixed.
All the requirements are met except the:
"Show Tooltips created in the applet builder" (backlog [ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-website/75))
