### ISSUE TITLE
The "Next" button is not replaced with the "Skip" on the item/items after selecting the "skippable item"/"allow user to skip all items" in the applet builder

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#329]
**Actual result:**
The "Skip" button is not appeared on the item/items after selecting the "skippable item"/"allow user to skip all items" in the applet builder:
1. Skippable item: https://www.screencast.com/t/T3tlOi8j7P
2. Allow user to skip all items: https://www.screencast.com/t/ZytlDy0m

**Expected result:**
1. The "Skip" button is displayed instead of the "Next" button on the particular item after selecting the "skippable item" in the applet builder
2. The "Skip" button is displayed instead of the "Next" button on the current item after selecting the "Allow user to skip all items" in the applet builder
3. [One-page assessment](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/512): If skippable is turned on, show a skip button in the usual place and have it look depressed once the user makes a selection

Environment:
https://web-staging.mindlogger.org/
josephine_ml@protonmail.com	qwertyui
applet: one page assessment
Allow user to skip all items: activity 7
Skippable item: activity 8
Applet password:	Qwe123!!!

**Comment by WorldImpex** [comment]
Fixed on Macbook pro/ chrome

**Comment by jj105** [comment]
could you please check it after clearing browser cache? ( it works fine on my windows/chrome )

**Comment by WorldImpex** [comment]
Works on windows/ firefox - blocked on windows chrome due to #354

**Comment by WorldImpex** [comment]
@jj105 It works on chrome now - I do have to hit submit twice to officially submit it. Could you look into that?

**Comment by jj105** [comment]
I see, I'll look into it

**Comment by WorldImpex** [comment]
works as expected
