### ISSUE TITLE
[Public Link that doesn't require an account] User is not able to take assessment without an account

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#333]
**Preconditions**
User is logged in on the admin panel
https://admin-staging.mindlogger.org/

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Proceed to the Invitation tab of applet that contain supported by webapp items
3. Generate an invitation that doesn't require an account
4. Copy invitation link 
5. Open invitation link as a non-logged in user in a new tab
6. Click on the activity
7. Pay attention to the screen

**Actual result**
User is not able to take assessment without an account. There is a blank page after clicking on the activity.

**Expected result**
User is able to take assessment without an account.

**Notes: There is 404 response after opening the link**

**Video (issue)**: https://www.screencast.com/t/A0GMte032p

**Video (logged in user, public link)**: https://www.screencast.com/t/o8ug2gWMcDJh

**Environment:**
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.82 
macOS 10.15 // Chrome 98.0.4758.82
 
owner: anita_ml@protonmail.com	qwe123!!!
applet: webapp applet name (anita)
public link: web-staging.mindlogger.org/applet/public/55ad31a0-0a02-4170

owner: kimberly_ml@protonmail.com	12345678
applet: PDF report test, PDF report

Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/1appSs0fU1U

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.82

**Comment by natalia-muzyka** [comment]
The issue is reproducible again on PROD and STAGING.
Video: https://www.screencast.com/t/znbfRKdG

**Environment:**
Win 10 // Chrome 101

https://web.mindlogger.org/
geria.test@gmail.com / 123456
subscales
bernard_ml@protonmail.com /	qwe123!!!
activity test

https://web-staging.mindlogger.org/
jeligi9407@zneep.com	123456
test applet

Applet password	Qwe123!!!

**Comment by devbtech** [comment]
I only deployed changes to prod. FYI @natalia-muzyka

**Comment by natalia-muzyka** [comment]
the issue is still reproducible on PROD (old and new account/applet): https://www.screencast.com/t/wOf2BNo5Esk
but not reproducible on STAGING: https://www.screencast.com/t/1FNxvTh9yXV
