### ISSUE TITLE
The "Invitation Removed" message is missing after clicking the "Decline invitation" on the public invitation page

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#345]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Proceed to the Invitation tab of any applet
3. Generate the public link that requires have an account
4. Open the public link in a new tab and log in
5. Click on the "Decline" button
6. Pay attention to the screen

**Actual result**
The "Invitation Removed" message is missing after clicking the "Decline invitation" on the public invitation page. User is redirected to the "Get started" page without any additional info.

**Expected result**
The "Invitation Removed" message is displayed after clicking the "Decline invitation" on the public invitation page. Expected behavior: https://www.screencast.com/t/7cx9FTNkDx4

**Video:** https://www.screencast.com/t/4jVBTywb7gAS

**Environment:**
https://web-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.82 
macOS 10.15 // Chrome 98.0.4758.82

**Comment by WorldImpex** [comment]
Fixed
