### ISSUE TITLE
Save screen size

### ISSUE THREAD

**Issue by akeshavan** [ChildMindInstitute/mindlogger-web#36]
We should also send the screen size when we send the responses. Some of those long voice passage tasks are harder to do on a small screen, people might read the passages slower when on their phone

**Comment by Eden2016** [comment]
Please clarify what functionality is related to this issue?

**Comment by shnizzedy** [comment]
@Eden2016, when a response is submitted, the app already sends back a `client` Object, eg,

```json
{
	"client": {
		"appId": "mindlogger-mobile",
		"appVersion": "0.9.8",
		"deviceModel": "iPhone XR",
		"os": "iOS",
		"osVersion": "13.3"
	}
}
```

This feature request is just to add the screen dimensions (width × height) to that Object.
