### ISSUE TITLE
[WEB] The applet image is repeated for every activity in the compared PDF report on website

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#361]
Video: https://www.screencast.com/t/R2lsJdsK

Expected: Applet image is displayed only at the very beginning of the report (if there's a splash screen then it goes right on the next page)

Environment:
https://web-staging.mindlogger.org/
loui_ml@protonmail.com 12345678
applet: daisy chain loop / activity 3
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
fixed

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![bandicam 2022-03-01 20-35-56-287.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/45abf1e4-d04c-4ac1-b855-ca27474044bf)

Environment:
https://web-staging.mindlogger.org/
loui_ml@protonmail.com 12345678
applet: daisy chain loop / activity 3
Applet password Qwe123!!!
