### ISSUE TITLE
change password form issues

### ISSUE THREAD

**Issue by astef021** [ChildMindInstitute/mindlogger-web#365]
environment: web-staging.mindlogger.org

1 - Error message is not displayed when old password and new password are same
2 - "Password must be at least 6 characters" is not translated into French
![image.png](https://images.zenhubusercontent.com/6181414bb17b332a2e8c0cb6/1e41971d-55c9-48f2-b40c-95e4b5469e8c)
3 - labels and input elements are not vertically aligned on mobile
![image.png](https://images.zenhubusercontent.com/6181414bb17b332a2e8c0cb6/a98ceb19-fcc1-4d86-baec-4e37daeb1be0)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/22157398-6e91-4a78-ab57-fdf77aae20e5)

https://web-staging.mindlogger.org/#/
Win 10 // Chrome 100.0.4896.127
