### ISSUE TITLE
UI issues in invitation page

### ISSUE THREAD

**Issue by astef021** [ChildMindInstitute/mindlogger-web#369]
environment: web-staging.mindlogger.org
device: iPhone 11

1 - color of logo image does not match background
![1.png](https://images.zenhubusercontent.com/6181414bb17b332a2e8c0cb6/918d2878-db5a-495a-95b4-e73a9f7294e3)

2 - font size for accept/decline buttons are too big on mobile ( title of buttons should be displayed in one row )
![2.png](https://images.zenhubusercontent.com/6181414bb17b332a2e8c0cb6/7c7ba933-6030-458f-b95b-7c63410346b5)

invitation url: 
https://web-staging.mindlogger.org/invitation/621c82026087568bd4c06eec

**Comment by natalia-muzyka** [comment]
1. nothing is changed,
@astef021 what the expected result should be? it's a little bit unclear

2. fixed on iPhone XS Max	15.3	1242x2688	6,5"	19.5:9
![bandicam 2022-03-02 12-16-10-976.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2da57385-ffd3-43d1-8ee3-f6460166f169)

still looks the same on Samsung Galaxy S7 SM-G930FD	8.0	1440x2560	5.1"	16:9
![bandicam 2022-03-02 12-26-53-948.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2d0aa9f0-3074-4807-a4f7-d7d7dcd744ea)

Suggest making the min-width and show Decline button below the Accept on small screens to avoid layout issue

**Comment by astef021** [comment]
1. the expected behavior for 1 is displaying white logo on mobile devices
https://cmi-logos.s3.amazonaws.com/ChildMindInstitute_Logo_Horizontal_KO.png

**Comment by natalia-muzyka** [comment]
@mtg137 
#1 fixed on the regular invitation page
#2 fixed on the regular and public invitation page

Issue #2: on the public invitation page logo is still blue on mobile devices

![bandicam 2022-03-03 11-33-59-999.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3a622d8b-1c23-41bb-bc42-c90c4e1f90ed)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![bandicam 2022-03-04 10-42-18-803.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/378dc694-1115-4406-8ac9-f0244326a668)

Environment:
Samsung Galaxy S7 // Android 8 // Chrome
iPhone Xs Max// iOS 15.3 // Chrome
