### ISSUE TITLE
There is no padding at the bottom of activity list

### ISSUE THREAD

**Issue by astef021** [ChildMindInstitute/mindlogger-web#370]
environment: web-staging.mindlogger.org

![image.png](https://images.zenhubusercontent.com/6181414bb17b332a2e8c0cb6/a3e91ff6-3461-453c-9848-5341040c71fb)

account: test_2@protonmail.com / 123456
applet: webapp schedule
device: iPhone 11

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![bandicam 2022-03-01 20-50-56-014.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3fc85191-1635-4d49-93ba-e16d3ce9e85f)

![bandicam 2022-03-01 20-51-12-600.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e80cee0b-2a63-4104-8ac1-b5a0d81459dc)

Environment:
web-staging.mindlogger.org
account: test_2@protonmail.com / 123456
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
