### ISSUE TITLE
Add back button in the page for taking assessment

### ISSUE THREAD

**Issue by astef021** [ChildMindInstitute/mindlogger-web#377]
environment: web-staging.mindlogger.org

![image.png](https://images.zenhubusercontent.com/6181414bb17b332a2e8c0cb6/f4efe813-a592-4fa6-b6f3-6e54e275ee2b)

Right now, there is no way to go back to activity list page and we have to go back to dashboard and find/click applet again to view activity list.

expected: there should be a back arrow on the left top side of page so user can go back to activity list page directly

**Comment by natalia-muzyka** [comment]
it is possible to move back with browser navigation, but I agree would be good to have an additional button,
video: https://www.screencast.com/t/HJoOp0e3f

**Comment by natalia-muzyka** [comment]
Works as expected. The "Back" button is added. After clicking on it user is moved back to the applet page.
Video: https://www.screencast.com/t/VZekQOOJ4lw2

Checked on:
Win 10 // Chrome 99.0.4844.51 
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
