### ISSUE TITLE
Endpoint to load a user's applets

### ISSUE THREAD

**Issue by akeshavan** [ChildMindInstitute/mindlogger-web#4]
@shnizzedy we need an endpoint that tells us which applet a user is assigned to

**Comment by akeshavan** [comment]
@shnizzedy to close this issue, take a look at where the function is called:

https://github.com/ChildMindInstitute/mindlogger-web/blob/master/src/components/AllApplets.vue#L48

and also where the route is defined:

https://github.com/ChildMindInstitute/mindlogger-web/blob/master/src/lib/api/api.js#L96

**Comment by shnizzedy** [comment]
Ref https://github.com/orgs/ChildMindInstitute/projects/9#card-18421913
