### ISSUE TITLE
[UI][Mobile][Portrait] Footer is not well adaptive on mobile devices

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#410]
Suggestion: on mobile devices / portrait mode rebuild the footer and show 2 elements or 1 element per row to avoid breaking the "Child mind Institute", "Matter Lab 2022" and "Terms of service"

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c9c41ada-fad9-4691-b3b9-b6dcc3604dd6)

Environment:
ML v0.19.2 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3

**Comment by natalia-muzyka** [comment]
@devbtech 
The "Child mind Institute" and "Terms of Service" links are missing in mobile view.
Video: https://www.screencast.com/t/MQ9MRDBH89xN

**Comment by WorldImpex** [comment]
We should have them in footer. We can get rid of the Child Mind Institute text and copyright C if that helps

**Comment by natalia-muzyka** [comment]
Verified as fixed. Only the "Child mind Institute" and "Terms of Service" links are displayed in the footer on mobile devices in portrait orientation. 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/bdf41eaf-6d06-4b2a-adae-2441ee42c1ba)

Environment:
https://web-staging.mindlogger.org/#/
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
