### ISSUE TITLE
login error on MindLogger Web

### ISSUE THREAD

**Issue by sanuann** [ChildMindInstitute/mindlogger-web#43]
I get this message on login:

Oh no! TypeError: Cannot convert undefined or null to object

Please file an issue on GitHub so we can fix this problem!

5c47d89bdedfea6af140e70c

**Comment by WorldImpex** [comment]
@binarybottle Do you remember this error? I wonder if it is reproducible any longer

**Comment by binarybottle** [comment]
I don't remember, and never ran into it myself.

**Comment by shnizzedy** [comment]
I just added a blocker ― this issue is for MindLogger web, which has not been functional since the massive schema changes in October.

**Comment by WorldImpex** [comment]
Deprecated since we are moving to react
