### ISSUE TITLE
Webapp [Mobile] [UI/UX] / Applet and activity page issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#43]
**1) The point(response) hasn't appeared after tapping on the slider** 
https://www.screencast.com/t/jSmRqaC67h
reproducible only for: iPhone 6 Plus // iOS 12.4.8 // 5.5" 1080 x 1920 pixels, 16:9 ratio

**2) The response options are too small on the mobile and not comfortable to interact with.**
Suggestions: 
-increase the space(margin-top and bottom) between response options, 
-set the response options font at least as on the mobile app
https://www.screencast.com/t/F56Nrngh
https://www.screencast.com/t/Ha7ar12wW

**3) Landscape: items with header images aren't comfortable to interact with.**
The response options are displayed too narrow.
Suggestion:
-to use the same view as in the portrait mode
https://www.screencast.com/t/n2OTxR2D
https://www.screencast.com/t/ilA2xTPH8
https://www.screencast.com/t/7610zcRr

**4) The header image isn't centered in the item block on the activity page**
https://www.screencast.com/t/vTb7yCFey

**5) The next item doesn't stack at the top after the user completed an item (user needs to scroll to see the current item)**	
https://www.screencast.com/t/af1y4BQF8N

**6) The slider's min and max labels are too narrow.**
https://www.screencast.com/t/VP2ZpHmmbkv
https://www.screencast.com/t/4LIhhEigWhc 
ChildMindInstitute/mindlogger-app#2 screenshot is reproducible only for Samsung S7 Edge // Android 8.0 // // Chrome 91.0.4471.120 // 5.5" 1440 x 2560 pixels, 16:9 ratio

**7) The active state for "Back" and "Next" buttons isn't always visible after tapping the button**	https://www.screencast.com/t/RmThOqL5i

**8) There is always a delay with displaying the image**	
https://www.screencast.com/t/RmThOqL5i

**9) The applet image has a larger width than the applet block**
@WorldImpex wdyt, shouldn't be better to use the displaying of applets list on the mobile devices as on the mobile app instead of blocks?
https://www.screencast.com/t/TGZxnPObzM

**10) Portrait: The image header is displayed without right margin**
https://www.screencast.com/t/i9IIBk7Nm4vm
Only for: Samsung S7 Edge // Android 8.0 // Chrome 91.0.4471.120 // 5.5" 1440 x 2560 pixels, 16:9 ratio

**Environment:**
https://web-staging.mindlogger.org/
geria2.test@gmail.com	// McgzF127
Applet / activity: Webapp test / multiple
iPhone 6 Plus // iOS 12.4.8 // Safari //  Chrome  92.0.4515.90 // 5.5" 1080 x 1920 pixels, 16:9 ratio
Samsung S7 Edge // Android 8.0 // Chrome 91.0.4471.120 // 5.5" 1440 x 2560 pixels, 16:9 ratio
iPhone 12 Pro Max	// iOS 14.4 //  //  Chrome  92.0.4515.90 // 6.7" 1284 x 2778 pixels, 19.5:9 ratio

**Comment by natalia-muzyka** [comment]
New issue:
**The response options with uploaded images are displayed out of the item block on the mobile devices**
Screenshot: https://www.screencast.com/t/GErVWrj9am
Environment:
Applet / activity: Webapp test / radio, multiple
iPhone 6 Plus // iOS 12.4.8 // Safari // Chrome 92.0.4515.90 // 5.5" 1080 x 1920 pixels, 16:9 ratio

**Comment by natalia-muzyka** [comment]
#3, 4, 6, 8, 9, 11 are fixed

**#1 Failed: The point now can be dragged, but if I tap it doesn't appear**
https://www.screencast.com/t/LslsISCN
iPad mini 4 WiFi	13.3.1	1536x2048	7.9"

**#2 The font size looks too big now on the desktop and tablets.**
Can we:
- use for desktop the previous font size
- use for mobile devices the same font size that in the mobile app (it is smaller than the current webapp font)

#5, #7 Still reproducible
https://www.screencast.com/t/t2GM8Ij7 

**New issues:**

**12) After fixing #2 the items with image header are now displayed too big on the tablets and desktop** 
https://www.screencast.com/t/X5xaKMVy
How it was implemented previously on desktop: 
https://www.screencast.com/t/9lEP7a8N

**13) The applet block(image, name, "About page" button) is overlapped with an activity list on the Applet page**
https://www.screencast.com/t/lzVEjlwZ
portrait: 
iPad mini 4 WiFi // iOS 13.3.1	// 1536x2048	// 7.9" // Safari
iPad Air 2 Wi-Fi // iOS 14.6 // 1536x2048 // 9.7" // Safari
Samsung Tab S6 // Android 9.0 // 1600 x 2560 // 10.5" // Chrome 92.0.4515.90
landscape: 
iPhone 12 Pro Max // iOS 14.4 // Safari // 6.7" 1284 x 2778 pixels, 19.5:9 ratio

**14) The applet block(image, name, "About page" button) is overlapped with an activity item on the Activity page**
portrait: 
iPad mini 4 WiFi // iOS 13.3.1	// 1536x2048	// 7.9"
iPad Air 2 Wi-Fi // iOS 14.6 // 1536x2048 // 9.7" 
landscape: 
iPhone 12 Pro Max // iOS 14.4 // Safari // 6.7" 1284 x 2778 pixels, 19.5:9 ratio

**Comment by natalia-muzyka** [comment]
@mtg137 new issues on the activity page:
15) the image 1920x1920 px is displayed out of the item block
https://www.screencast.com/t/XbscPZUaA
16) there is no indent between the header image and text (large text)
https://www.screencast.com/t/iVVxkvWV2F

Win 10 // Chrome 92.0.4515.107 
geria2.test@gmail.com	// McgzF127

**Comment by natalia-muzyka** [comment]
Low UI issues that would be good to fix:

**17) The applet image isn't centered on the activity page**
https://www.screencast.com/t/mjyh1NQ5
iPad Air 2 Wi-Fi // iOS 14.6 // Safari // 1536x2048 // 9.7"

**18) The response text isn't vertically aligned with the response button**
https://www.screencast.com/t/PQkUPRD1
iPad Air 2 Wi-Fi // iOS 14.6 // Safari // 1536x2048 // 9.7"

**19) The applet list isn't centered (or divided into two columns) on the applet page**
https://www.screencast.com/t/CHM95TKY
Samsung Tab S6 // Android 9.0 // 1600 x 2560 // 10.5" // Chrome 92.0.4515.131

**20) The loader isn't centered on the applet page (while downloading the applet list)**
https://www.screencast.com/t/rZhQZnSsmRr
Samsung Tab S6 // Android 9.0 // 1600 x 2560 // 10.5" // Chrome 92.0.4515.131
Samsung S7 Edge // Android 8.0 // Chrome 9 // 5.5" 1440 x 2560 pixels, 16:9 ratio
iPhone 7	// iOS 13.1.1 // 750x1334 // 4,7'' 16:9 ratio

**21) The line-height isn't similar for all the responses in the list if there are more than 3 response options.** 
https://www.screencast.com/t/1V4UPmEDza
Samsung Tab S6 // Android 9.0 // 1600 x 2560 // 10.5" // Chrome 92.0.4515.131
Samsung S7 Edge // Android 8.0 // Chrome 9 // 5.5" 1440 x 2560 pixels, 16:9 ratio

**22) The response buttons are trimmed on the top in Safari**
https://www.screencast.com/t/O999emS550
iPad Air 2 Wi-Fi // iOS 14.6 // Safari // 1536x2048 // 9.7"

**23) [Portrait] Small screens: The "Back" and "Next"/"Submit" buttons are displayed too close or on separate rows but aren't centered**
https://www.screencast.com/t/ubxe2PVt
iPhone 7	// iOS 13.1.1 // 750x1334 // 4,7'' 16:9 ratio
Samsung S7 Edge // Android 8.0 // Chrome 92.0.4515.131 // 5.5" 1440 x 2560 pixels, 16:9 ratio

@WorldImpex Please, let me know should these issues be fixed in the scope of the current release or it should go to the backlog, thank you!

**Comment by WorldImpex** [comment]
@natalia-muzyka Yes lets try to fix these issues before launch.

**Comment by HarutQA** [comment]
Works as it should be on Android Redmi Note 9, iOS iPhone 11 pro.
