### ISSUE TITLE
Add 'time' input type

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-web#49]
Like the 'timerange' input type, but just for one time.

ex1: About what time did you go to bed last night?

X:XX AM/PM

**Comment by binarybottle** [comment]
This issue is reiterated in issue #280 with more information there, so closing this issue.

**Comment by shnizzedy** [comment]
This issue is for the web app, https://github.com/ChildMindInstitute/mindlogger-app/issues/280 is for the mobile app. Reopening.

**Comment by hotavocado** [comment]
this has been resolved, 'time' input type is now working on applets

**Comment by WorldImpex** [comment]
Resolved per @hotavocado
