### ISSUE TITLE
⬆️ Update reprolib prefixes to `reprolib:`

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-web#51]
- [src/components/AppletParentRoute.vue](https://github.com/ChildMindInstitute/mindlogger-web/blob/a5c6ec48bc2a30ca1d5f476f4d8be4d389d2b23b/src/components/AppletParentRoute.vue) has a bunch of keys to update.
- [src/components/Visualization/ItemPlot/ItemPlot.vue](https://github.com/ChildMindInstitute/mindlogger-web/blob/476ec2fe42ff39a4eb6a88744deaea1bdb7dcece/src/components/Visualization/ItemPlot/ItemPlot.vue) has several.
- [src/components/Visualization/ActivityDash/ActivityDash.vue](https://github.com/ChildMindInstitute/mindlogger-web/blob/476ec2fe42ff39a4eb6a88744deaea1bdb7dcece/src/components/Visualization/ActivityDash/ActivityDash.vue#L36-L37) has a couple.

*Caveat*: Many of these keywords are out of date since [reprolib added a level of nesting to the schema about a month ago](https://github.com/ReproNim/schema-standardization/pull/265). Eg, what we have as `repronim:isAbout` is now `repronim:terms/isAbout`.

_Originally posted by @shnizzedy in https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/207#issuecomment-547973883_

**Comment by shnizzedy** [comment]
#59 will resolve this issue, but so much has changed since October 7, 2019, that that PR needs a little more work before it's ready to merge and deploy.

**Comment by shnizzedy** [comment]
I see this [marked as PR Review Ready](https://github.com/ChildMindInstitute/mindlogger-web/issues/51#zh-event-5e2457e9feaeccd1a408b08e), but I know [I didn't finish before I had to set it aside](https://github.com/ChildMindInstitute/mindlogger-web/issues/51#issuecomment-573720307).

**Comment by devbtech** [comment]
Moving this from **`PR Review Ready`** to **`Backlog`** since this is DRAFT and wasn't fully finished yet.

**Comment by WorldImpex** [comment]
Deprecated since we are moving to react
