### ISSUE TITLE
The option response, button and image aren't vertically aligned for the radio button, checkbox item type

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#52]
**Steps to reproduce**
1. Open a site https://web-staging.mindlogger.org/
2. Log in geria2.test@gmail.com // McgzF127
3. Proceed to the activity with radio button, checkbox options with uploaded images
4. Pay attention to the screen

**Actual result**
The option response, button and image aren't vertically aligned for the radio button, checkbox item type

**Expected result**
The option response, button and image are vertically aligned(middle) for the radio button, checkbox item type

**Screenshots:**
https://www.screencast.com/t/qmiwuyAzKL9
https://www.screencast.com/t/Zuk5fy1f

**Environment**
https://web-staging.mindlogger.org/
https://admin-staging.mindlogger.org/
account (owner): geria2.test@gmail.com // McgzF127
applet / activity: webapp test / radio, checkbox, multiple
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
looks great for one-row response options
https://www.screencast.com/t/RsJm4DJuWq

@mtg137 could you, please, align the images so they will be displayed in the same row with a button?
https://www.screencast.com/t/lzaa6vC8im7

**Comment by mtg137** [comment]
sure, I'll update it.

**Comment by natalia-muzyka** [comment]
verified as fixed
https://www.screencast.com/t/yZBlElOPx8

Environment
https://web-staging.mindlogger.org/
https://admin-staging.mindlogger.org/
account (owner): geria2.test@gmail.com // McgzF127
applet / activity: webapp test / radio, checkbox, multiple
Applet password: Qwe123!!!
