### ISSUE TITLE
The site "https://web-staging.mindlogger.org/" has a 404 error.

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-web#533]
The site "https://web-staging.mindlogger.org/" has a 404 error.

Screenshot:
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/2832067b-91a9-4ef4-8fc9-66d32935de72)

Environment:
https://web-staging.mindlogger.org/

**Comment by natalia-muzyka** [comment]
The issue is till reproducible on staging;

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a5b2b4cc-ebca-4861-afcd-b0fa6dacebd8)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2c0da110-a10f-461a-ab93-8c7351189271)
