### ISSUE TITLE
The activity stays "In progress" after submitting the response

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#55]
**Steps to reproduce**
1. Open a site https://web-staging.mindlogger.org/
2. Log in geria.test@gmail.com // 123456
3. Complete any activity (e.g. Webapp test / radio)
4. Proceed to the applet screen with this activity
5. Pay attention to the activity status

**Actual result**
The activity stays "In progress" after submitting the response

**Expected result**
The activity gets the proper status(according to the scheduling state) after submitting the response

**Video:** 
https://www.screencast.com/t/3BvFUdd949
https://www.screencast.com/t/KcQhmABekFL

**Environment**
https://web-staging.mindlogger.org/
Win 10 // Chrome 92.0.4515.107
macOS 10.15.6 // Safari 13.1.2 (15609.3.5.1.3)
geria2.test@gmail.com // McgzF127

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/6Z231dywjp

Environment
https://web-staging.mindlogger.org/
Win 10 // Chrome 92.0.4515.107
geria2.test@gmail.com // McgzF127

**Comment by natalia-muzyka** [comment]
The issue is reproducible again.
Currently, the activity is displayed as "in progress" after submitting the responses only after the first attempt to complete the activity. After the second attempt responses are submitted.
Video: https://www.screencast.com/t/MCyrDTokQC

Environment:
https://web-staging.mindlogger.org/
avani_ml@protonmail.com // 12345678
applet: cumulative scores webapp, tokenlogger

**Comment by natalia-muzyka** [comment]
Verified as fixed
Video: https://www.screencast.com/t/ttqqlxwqxll

Environment:
https://web-staging.mindlogger.org/
avani_ml@protonmail.com // 12345678
applet: cumulative scores webapp, tokenlogger

**Comment by natalia-muzyka** [comment]
@jj105 The issue is reproducible on **prod**

Environment:
https://web.mindlogger.org/
account: 
bernard_ml@protonmail.com	// qwe123!!!
applet: Pediatric Screener (PCS) Parent-Report HBN (1)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@jj105 @devbtech was this fix deployed to staging? I couldn't reproduce it on staging, only in the particular applet on production.
https://www.screencast.com/t/rnxlPe70

**Comment by natalia-muzyka** [comment]
@devbtech @jj105 
the issue is still reproducible on production: https://www.screencast.com/t/2jZQrUo7TQ1

Demo ML account
applet: pediatric Screener (PCS) Parent-Report HBN (1)

**Comment by natalia-muzyka** [comment]
@jj105 @devbtech shouldn't this fix be deployed to production? I couldn't reproduce this issue on staging, so I can't check if it is fixed.

**Comment by natalia-muzyka** [comment]
Ticket should be closed because the issue was caused by empty subscales issue,
(there was an issue with slash "/" that broke subscales at all)

**Comment by natalia-muzyka** [comment]
@jj105 the issue is not reproducible anymore: 
https://www.screencast.com/t/MB9ICTJol

**Comment by jj105** [comment]
yeah, there was an issue with submitting responses on web app side. it is fixed in PRs we deployed yesterday.
