### ISSUE TITLE
Webapp Text Activity

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#6]
* If an activity is selected then show the first item type
* When the user completes an item, the next item should stack at the top so the user does not have to scroll unless he or she wants to see previously answered questions 
* Allow the user to change previously-stored answers by selecting back which will move the selected question and editability backward until the user is at the item that should be edited. 
* Text is the only items in scope for this effort 
** Correct Answer Required needs to work on webapp
* Show a confirmation screen after the user hits submit 
* If the user navigates away from the webapp and comes back later to restart an activity, show a confirmation pop like on mobile "Resume Activity - Would you like to resume this activity in progress or restart?" With Restart and Resume buttons 
* Display header and response option images 
* Show Tooltips created in the applet builder

**Comment by natalia-muzyka** [comment]
@devbtech web app text activity can be tested separately? could you clarify, please, how fast do we get a deployment for all the item types?

**Comment by natalia-muzyka** [comment]
testing is blocked by [The newly created activity within an existing applet, newly created/duplicated applet aren't shown up on the web-staging#73](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-website/73)

**Comment by natalia-muzyka** [comment]
All the issues are fixed.
All the requirements are met except the:
"Show Tooltips created in the applet builder" (backlog [ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-website/75))
