### ISSUE TITLE
Firefox.The Network Error occurs after trying to log in to the site

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-web#64]
**Preconditions:**
The user is registered on the site  https://web.mindlogger.org/#/
**Steps to reproduce:**
1. Open the site https://web.mindlogger.org/#/
2. Click the "Log in" button
3. Specify your credentials and click the 'Submit' button (qwer //123456)
4. Pay attention to the result

Actual result: The network error occurs after trying to log in to the site
https://www.screencast.com/t/6Ur48ZlY6
Expected result: The user should be able to log in to the site successfully

**Environment:**
Win 10 x64 
Browser: Firefox 75

**Comment by WorldImpex** [comment]
fixed
