### ISSUE TITLE
Show Scheduled and Unscheduled Activities

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#8]
@WorldImpex commented on [Mon May 18 2020](https://github.com/ChildMindInstitute/mindlogger-website/issues/37)

As a user, I want to see activities that are available to me so that I know what I can take or will take in the future that day. 

Requirements 
* When the user hits "Get Started" on the landing page, show a page with available applets the user has access to 
* Non/ Scheduled Activities: When the user clicks on the applet icon, navigate the user to a page with available activities to be completed that change status like the mobile app 
* Show the applet image icon and name of the applet and description 
* Show activities, descriptions and scheduling state 
* Show an about page button
** If the user clicks show a popup with the details of the about page 

![WebApp.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f398493a-9201-494a-b8cb-599e21ba9f6d)

**Comment by natalia-muzyka** [comment]
Issues:
[The "Past due" activity status is displayed for available activities on the website #100](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/100)

**Comment by natalia-muzyka** [comment]
Issues are fixed,
verified and closed.
