### ISSUE TITLE
Markdown webapp issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#88]
**Steps to reproduce**
1. Open a site https://web-staging.mindlogger.org/
2. Log in: johndoeregress@protonmail.com	// 12345678
3. Start the activity with markdown text (new markdown text)
4. Pay attention to the screen

**Actual result**
The markdown text is displayed with issues:
the underline, strikethrough, mark, superscript, subscript, clamp to the left/center/right, quote, table, code, audio (uploaded and link) aren't correctly displayed on the website.

**Expected result**
The markdown text is displayed correctly (as in the applet builder preview window)

**Screenshot:**
https://www.screencast.com/t/gb4KyRJi22gK

**Environment**
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 // Chrome 92.0.4515.107 
johndoeregress@protonmail.com	// 12345678
applet: new markdown text
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
The next elements aren't displayed as expected
1) the marked (yellow) text overlaps the above row https://www.screencast.com/t/Zcjcaekve0
2) underlined text is displayed raw 
3) uploaded audio file can't be played

For #2 and #3 the same behavior is in the applet builder, so I put these in the separate [ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/457) for the applet builder

Environment
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 // Chrome 92.0.4515.107
johndoeregress@protonmail.com // 12345678
applet: new markdown text
Applet password: Qwe123!!!

**Comment by HarutQA** [comment]
bug is still reproducible.

**Comment by mtg137** [comment]
I think 2) and 3) are scope of [applet builder issue](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/457)

( content is not uploaded correctly on applet builder, and it's why we are experiencing 2) and 3) on web app )

**Comment by HarutQA** [comment]
Works correctly.
