### ISSUE TITLE
Setup Conditional Logic for available items

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web#9]
As a user, I want to interact with conditional questions so that I can have a curated experience. 

Requirements 
* Conditional logic works for the radio button, checkbox, slider, and textbox items
* If a user goes back to a question and changes the condition then conditional questions are shown or not shown based on the response selected by the user

**Comment by natalia-muzyka** [comment]
Conditional logic issues
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/49

**Comment by natalia-muzyka** [comment]
verified and closed
