### ISSUE TITLE
The uploaded watermark is displayed above the active item instead of on the top left active item's corner 

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-web#91]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Create a new applet with at least one activity
3. Add a watermark 101.jpg
4. Save the activity
5. Complete the activity with a watermark on the website
6. Pay attention to the screen

**Actual result**
The uploaded watermark is displayed above the active item instead of on the top left active item's corner 

**Expected result**
The uploaded watermark is displayed on the top left active item's corner. Mockup:
https://www.screencast.com/t/yqIDUtuzYE

**Video:** https://www.screencast.com/t/SAdBOT3x

**Environment**
https://web-staging.mindlogger.org/
Win 10 // Chrome 92.0.4515.107
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 6 Plus // iOS 12.3.1
geria2.test@gmail.com // McgzF127
applet: watermark test, watermark test new, watermark from URL
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@Matchdev120 could you fix the next two issues, please:
- watermark should have the same positioning on the item's cart (margin-top, margin-left):
https://www.screencast.com/t/M8OiiiuFUY
- watermark should be displayed only on the active item (on the top)

Could you check with @mtg137 , please, if the latest changes regarding the watermark broke the item's layout?
After implementing the watermark I'm experiencing new UI issues on the activity page (described [here](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/43) in the latest comment)

Thank you)

**Comment by Matchdev120** [comment]
@natalia-muzyka Are all the issues are related to watermark?

**Comment by Matchdev120** [comment]
@natalia-muzyka Did you experience the issues before implementing watermark?

**Comment by natalia-muzyka** [comment]
@Matchdev120 , no, I didn't.

**Comment by natalia-muzyka** [comment]
Verified as fixed

Environment
https://web-staging.mindlogger.org/
Win 10 // Chrome 92.0.4515.107
macOS 10.15.6 // Safari 13.1.2 (15609.3.5.1.3)
geria2.test@gmail.com // McgzF127
applet: multiple
Applet password: Qwe123!!!
